ALTER TABLE account DROP COLUMN owner_name;

ALTER TABLE transaction 
    ADD COLUMN IF NOT EXISTS status VARCHAR(255) NOT NULL DEFAULT 'PENDING';

ALTER TABLE transaction
    ADD COLUMN IF NOT EXISTS observations VARCHAR(255) NOT NULL DEFAULT '';